const LOGIN_REG_STARTS = "LOGIN_REG_STARTS";
const LOGIN_REG_SUCCESS = "LOGIN_REG_SUCCESS";
const LOGIN_REG_FAIL = "LOGIN_REG_FAIL";

const LOGOUT = "LOGOUT";

export { LOGIN_REG_FAIL, LOGIN_REG_SUCCESS, LOGIN_REG_STARTS, LOGOUT };
