import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Layout } from "../components/Layout/Layout";
import { theme } from "../theme";
import { ThemeProvider } from "@mui/material";
import Head from "next/head";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import { CacheProvider, EmotionCache } from "@emotion/react";
import createEmotionCache from "../utils/createEmtotionCache";
import CssBaseline from "@mui/material/CssBaseline";

const clientSideEmotionCache = createEmotionCache();
interface MyAppProps extends AppProps {
    emotionCache?: EmotionCache;
}
import { StylesProvider, createGenerateClassName } from "@mui/styles";

const generateClassName = createGenerateClassName({
    productionPrefix: "c",
});

export default function App({
    Component,
    pageProps,
    emotionCache = clientSideEmotionCache,
}: MyAppProps) {
    return (
        <StylesProvider generateClassName={generateClassName}>
            <CacheProvider value={emotionCache}>
                <Provider store={store}>
                    <ThemeProvider theme={theme}>
                        <Head>
                            <title>Create Next App</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/favicon.ico" />
                        </Head>
                        <CssBaseline />
                        <Layout>
                            <Component {...pageProps} />
                        </Layout>
                    </ThemeProvider>
                </Provider>
            </CacheProvider>
        </StylesProvider>
    );
}
