import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Layout } from "../components/Layout/Layout";
import { theme } from "../theme";
import { ThemeProvider } from "@mui/material";
import Head from "next/head";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import { CacheProvider, EmotionCache } from "@emotion/react";
import createEmotionCache from "../utils/createEmtotionCache";
import CssBaseline from "@mui/material/CssBaseline";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import "../styles/animate.css";
import "../styles/select2.css";
import "../styles/style.css";

const clientSideEmotionCache = createEmotionCache();
interface MyAppProps extends AppProps {
     emotionCache?: EmotionCache;
}
import { StylesProvider, createGenerateClassName } from "@mui/styles";
import { useEffect } from "react";
// import Script from "next/script";

const generateClassName = createGenerateClassName({
     productionPrefix: "c",
});

export default function App({
     Component,
     pageProps,
     emotionCache = clientSideEmotionCache,
}: MyAppProps) {
     useEffect(() => {
          require("bootstrap/dist/js/bootstrap.bundle.min.js");
     }, []);

     return (
          <StylesProvider generateClassName={generateClassName}>
               <CacheProvider value={emotionCache}>
                    <Provider store={store}>
                         <ThemeProvider theme={theme}>
                              <Head>
                                   <title>Create Next App</title>
                                   <meta
                                        name="description"
                                        content="Generated by create next app"
                                   />
                                   <link rel="icon" href="/favicon.ico" />
                                   <meta
                                        name="viewport"
                                        content="width=device-width, initial-scale=1"
                                   />
                              </Head>
                              <CssBaseline />
                              <Layout>
                                   <Component {...pageProps} />
                                   {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" /> */}
                              </Layout>
                         </ThemeProvider>
                    </Provider>
               </CacheProvider>
          </StylesProvider>
     );
}
