import { Theme, useTheme } from "@mui/material";
import { makeStyles } from "@mui/styles";

export const useSchedulerStyles = makeStyles((theme: Theme) => ({
     container: {
          width: "100%",
          display: "flex",
          alignItem: "center",
          justifyContent: "center",
          marginBottom: 10,
     },
     root: {
          width: "90%",
          borderRadius: 10,
     },
     form: {
          width: "100%",
          backgroundColor: "#fafafa",
          padding: "32px",
          display: "flex",
          alignItem: "flex-end",
          justifyContent: "space-between",
          gap: 16,
          flexWrap: "wrap",
          borderRadius: 10,
     },
     tabContainer: {
          display: "flex",
          alignItem: "center",
          justifyContent: "flex-start",
          gap: 4,
          marginBottom: 4,
     },
     tab: {
          backgroundColor: "#00a99d",
          color: "#fff",
          fontWeight: 600,
          padding: "12px 32px",
          cursor: "pointer",
          textTransform: "capitalize",
          fontSize: 16,
          display: "flex",
          alignItem: "center",
          justifyContent: "center",
          gap: 16,
          borderRadius: 5,

          "&:hover": {
               color: "#fff",
               backgroundColor: "#06d0c2",
          },
     },
     activeTab: {
          gap: 16,
          fontSize: 16,
          backgroundColor: "#fff",
          color: "#00a99d",
          fontWeight: 600,
          padding: "12px 32px",
          cursor: "pointer",
          display: "flex",
          alignItem: "center",
          justifyContent: "center",
          textTransform: "capitalize",
          borderRadius: 5,

          "&:hover": {
               color: "#00a99d",
               backgroundColor: "#fff",
          },
     },
     select: {},
     inputContainer: {
          minWidth: 100,
          flex: 1,
          display: "flex",
          alignItem: "flex-end",
          justifyContent: "flex-end",
          flexDirection: "column",
          position: "relative",

          "& > label": {
               fontFamily: "Raleway",
               fontSize: 14,
               color: "#636363",
               lineHeight: 1,
               paddingBottom: 10,
               display: "block",
               fontWeight: 600,
               marginBottom: 0,
               whiteSpace: "nowrap",
          },
     },
     searchBtn: {
          backgroundColor: "#00a99d !important",
          color: "#fff !important",
          padding: "8px 40px !important",
          fontFamily: "Raleway",
          fontSize: "14px !important",
          lineHeight: 1,
          fontWeight: "600 !important",
          whiteSpace: "nowrap",
          display: "flex",
          alignItem: "center",
          justifyContent: "center",
          maxWidth: 150,
          margin: "0 !important",
     },
     dateRangeInput: {
          background: "none",
          outline: 0,
          backgroundColor: "#fff !important",
          height: 38,
          border: "1px solid hsl(0, 0%, 80%)",
          borderRadius: 4,
          padding: "0px 8px",
          color: "#636363",
     },
     calenderContainer: {
          position: "absolute",
          zIndex: 100,
          top: "calc(100% + 10px)",
     },
     calendar: {
          borderRadius: 10,
          overflow: "hidden",
          fontFamily: "Raleway",
          fontSize: 12,
          color: "#636363",
          lineHeight: 1,
          paddingBottom: 10,
          display: "block",
          fontWeight: 600,
          marginBottom: 0,
          whiteSpace: "nowrap",

          "& .react-calendar__tile--now": {
               backgroundColor: "#00a99d",
               color: "#fff",
               borderRadius: "4px 0px 0px 4px",
          },

          "& .react-calendar__tile:disabled": {
               backgroundColor: "#fff",
               opacity: 0.5,
          },

          "& .react-calendar__tile--rangeEnd": {
               backgroundColor: "#00a99d",
               color: "#fff",
               borderRadius: "0px 4px 4px 0px",
          },

          "& .react-calendar__tile--active": {
               backgroundColor: "#00a99d",
          },

          "& .react-calendar__month-view__weekdays": {
               color: "#636363",
               fontFamily: "Raleway",
               fontSize: 14,
          },

          "& .react-calendar__navigation__arrow": {
               fontFamily: "Raleway",
               fontSize: 20,
               color: "#636363",
               lineHeight: 1,
               fontWeight: 600,
               marginBottom: 0,
               whiteSpace: "nowrap",
               display: "flex",
               alignItems: "center",
               justifyContent: "center",
               padding: "0px 16px",
               borderRadius: 4,
               margin: "0px 4px",
          },
     },
}));
